//
//  GreetingInteractor.swift
//  CleanSwift Example
//
//  Created by Арсентий Халимовский on 14.05.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GreetingBusinessLogic {
    func doSomething(request: Greeting.ShowGreeting.Request)
}

protocol GreetingDataStore {
    //var name: String { get set }
}

class GreetingInteractor: GreetingBusinessLogic, GreetingDataStore {
    
    var presenter: GreetingPresentationLogic?
    var worker: GreetingWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Greeting.ShowGreeting.Request) {
        worker = GreetingWorker()
        worker?.doSomeWork()
        
        let response = Greeting.ShowGreeting.Response()
        presenter?.presentSomething(response: response)
    }
}
