//
//  GreetingInteractor.swift
//  CleanSwift Example
//
//  Created by Арсентий Халимовский on 14.05.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GreetingBusinessLogic {
    func ShowGreeting(request: GreetingRequest)
}

protocol GreetingDataStore {
    var person: Person? { get }
}

class GreetingInteractor: GreetingBusinessLogic, GreetingDataStore {
    
    var presenter: GreetingPresentationLogic?
    var person: Person?
    // var worker: GreetingWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func ShowGreeting(request: Greeting.ShowGreeting.Request) {
        person = Person(name: "Tim", surname: "Cook")
        let name = person?.name ?? ""
        let surname = person?.surname ?? ""
        let response = GreetingResponse(name: name, surname: surname)
        presenter?.presentGreeting(response: response)
    }
}
