//
//  GreetingRouter.swift
//  CleanSwift Example
//
//  Created by Арсентий Халимовский on 14.05.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


// Don't need for this project but will be an example for bigger projects
import UIKit

// Router logic
@objc protocol GreetingRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

// Data passing
protocol GreetingDataPassing {
    var dataStore: GreetingDataStore? { get }
}

// Router
class GreetingRouter: NSObject, GreetingRoutingLogic, GreetingDataPassing {
    
    // Hold View Controller
    weak var viewController: GreetingViewController?
    var dataStore: GreetingDataStore?
    
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?) {
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: GreetingViewController, destination: SomewhereViewController) {
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: GreetingDataStore, destination: inout SomewhereDataStore) {
    //  destination.name = source.name
    //}
}
