//
//  GreetingModels.swift
//  CleanSwift Example
//
//  Created by Арсентий Халимовский on 14.05.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// ViewModel
typealias GreetingViewModel = Greeting.ShowGreeting.ViewModel
// Response
typealias GreetingResponse = Greeting.ShowGreeting.Response
// Request
typealias GreetingRequest = Greeting.ShowGreeting.Request


enum Greeting {
    // MARK: Use cases
    
    enum ShowGreeting {
        // broker between ViewController and Interactor
        struct Request {
        }
        // broker between Interactor and Presenter
        struct Response {
            let name: String
            let surname: String
        }
        // broker between Presenter and ViewController
        struct ViewModel {
            let greeting: String
            
        }
    }
}
