//
//  GreetingPresenter.swift
//  CleanSwift Example
//
//  Created by Арсентий Халимовский on 14.05.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GreetingPresentationLogic {
    func presentSomething(response: Greeting.Something.Response)
}

class GreetingPresenter: GreetingPresentationLogic {
    
    weak var viewController: GreetingDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Greeting.Something.Response) {
        let viewModel = Greeting.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
