//
//  GreetingPresenter.swift
//  CleanSwift Example
//
//  Created by Арсентий Халимовский on 14.05.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GreetingPresentationLogic {
    func presentGreeting(response: Greeting.ShowGreeting.Response)
}

class GreetingPresenter: GreetingPresentationLogic {
    
    weak var viewController: GreetingDisplayLogic?
    
    // MARK: Do something
    
    func presentGreeting(response: Greeting.ShowGreeting.Response) {
        let greeting = "Hello, \(response.name) \(response.surname)!"
        let viewModel = GreetingViewModel(greeting: greeting)
        viewController?.displayGreeting(viewModel: viewModel)
    }
}
